### ISSUE TITLE
If there are too many characters in the paragraph, there will be lag and unsmoothness.

### ISSUE THREAD

**Issue by shuen2023** [plu5/retype#15]
The books I use to practice typing are in Chinese.  I noticed that when there are too many characters in a paragraph, there will be lag and unsmoothness.

**Comment by plu5** [comment]
Thanks for the report! I made a test epub with long lines and I am seeing this issue too; long lines cause input lag. I think this is a fundamental design issue in retype because the text is split to lines. I think what I will try to do is make it a setting so you can change what characters split the text, and maybe make it so "." or "。" characters split it also, not just newline.
