### ISSUE TITLE
Progress is only saved at the end of a line/paragraph

### ISSUE THREAD

**Issue by xp12047** [plu5/retype#4]
Well, when I closed and then opened, the original progress started again..

https://user-images.githubusercontent.com/56335408/204469526-9b1632dc-00ee-47a1-b4af-0ed80903fada.mp4

**Comment by plu5** [comment]
Progress is saved when you reach the end of the sentence (on newline / new paragraph)

**Comment by xp12047** [comment]
> 当您到达句子结尾时（在换行符/新段落上），进度会被保存

It turned out to be like this.  So is there a way not to save by paragraph?  Save anytime?

**Comment by xp12047** [comment]
Sorry, I don't speak English, so I can only use translation software.  So some expressions may not be good.

**Comment by plu5** [comment]
At the moment no. The text is split into lines, and you only progress at the end of each line. I made it this way so that it exercises the user's ability to handle the entire sentence, like when typing real text; you might make a typing mistake at the start of a sentence but not notice and continue typing, then you have to go back and correct it.

The downside is if there is a lot of text on one line. I may try to think of a different way of doing it. I don't really want to break it up on words though.

No worries about language, I can understand you well so far. And it's an honour to have you using my software :-)
